### ISSUE TITLE
[streamlit prototype] HTML -> Markdown converter

### ISSUE THREAD

**Issue by Elijas** [alphanome-ai/sec-ai#43]
a useful thing to build in sec-ai would be a simple streamlit app that can convert the whole document to a txt file, as the txt file could then be used for any LLM applications (langchain, chatgpt file upload, etc)

[notebook1](https://github.com/Elijas/sec-parser-exploration/blob/main/00_mdna.ipynb) This illustrates text being converted to markdown
[notebook2](https://github.com/Elijas/sec-parser-exploration/blob/main/01_nested_tables_to_markdown.ipynb) illustrates tables being converted to markdown
putting the two together into a streamlit app would give us an HTML -> markdown converter for SEC EDGAR documents

### bonus objective
think about how it would be most convenient to use, would it be multiple file upload? multiple URL paste? Maybe integrate `sec-edgar-downloader` and ability to search for companies, and ability to select multiple past reports of those companies?

**Comment by rishirishhh** [comment]
Would like to work on this

**Comment by Elijas** [comment]
Awesome! Join our Discord if you haven't already (the [#sec-ai](https://discord.gg/6K9Xtapm) channel).

P.S. For a quick start, feel free to use (just copy-paste relevant things) from the SEC EDGAR URL input field implemented here
- https://github.com/alphanome-ai/sec-parser/tree/main/dev_utils/semantic_visualization 

<img width="392" alt="image" src="https://github.com/alphanome-ai/sec-ai/assets/4084885/07c12396-61da-470c-913f-4d18f55f0f8d">

Let's develop this converter iteratively: create a PR for the initial version, and together we'll explore ways to enhance its usefulness even further.

**Comment by rishirishhh** [comment]
I am done with the setup for the project

**Comment by Elijas** [comment]
Glad to hear 🙌  Now go ahead and create a new folder and a new python file inside the `dev_utils` folder. This new python file will be your streamlit application.

The user of the application should be able to paste the link
![image](https://github.com/alphanome-ai/sec-ai/assets/4084885/a35a0a9c-cb85-49d7-8e5a-b801ed01c4c7)

And somehow have a `result.md` file downloaded to his computer (maybe a button "Download" ?)

Let me know what you think about this plan, we can definitely change it! And please ask further questions, if you have any 🚀

**Comment by Elijas** [comment]
@mutton_biryani Let's start with the "why". Uploading raw HTML files makes it more difficult and expensive for ChatGPT to process it, so we want to "clean it up" by just getting the text while keeping all the relevant structural information.

We'll build a simple application where users can preprocess SEC EDGAR files to be uploaded to ChatGPT. 

Let's work through [the task](https://github.com/alphanome-ai/sec-ai/issues/43) step by step:

1. Out application needs to take in one SEC filing report URL, automatically download the filing, convert it using sec-parser, then convert each parsed element to a text, and then join the results together into a single text file
2. There is already code for all the major pieces, so you pretty much need just to copy-paste the things together 
3. First we will need to prototype in some way. Start by creating a [streamlit application](https://streamlit.io/), by just creating a new python file in `dev_utils` folder or you can create a single ipynb notebook in the `dev_utils` folder. In there. 
- Start by downloading the given HTML source code from the given URL
4. Then you will need to convert the source code HTML into a Python List of Elements. Use [sec-parser](https://github.com/alphanome-ai/sec-parser).
5. For each element in the List of Elements, extract the text from it using the object methods (e.g. `element.text`)
6. Join all elements into a single text piece to allow the user to copy the result or download it as a file

There are further steps but let's start with this initial pipeline for now. Let me know if you'd like more specific initial steps, or if you have any questions :raised_hands:

**Comment by Elijas** [comment]
Closing, as per our chat in the Discord 👍
