### ISSUE TITLE
create requirement.txt for the project

### ISSUE THREAD

**Issue by Anash3** [alphanome-ai/sec-ai#5]
create a requirement.txt file for the project

**Comment by KakkoAki** [comment]
Hi Anash, great to have you here, we are currently working on and tomorrow we will provide for both projects sec-parser (for quality data) and sec-ai:
- Introduction to Contribution (technical background)
- A Roadmap to the Project's Journey (outlines our vision and direction)

**Comment by Elijas** [comment]
Hello and welcome to the project! 🎉 We're thrilled you're interested in contributing.

We use **Poetry** for managing dependencies, which makes setting up the project smooth and easy.

### Quick Steps to Get Started:
1. **Install Poetry**: If you haven't installed it yet, follow the instructions on [this GitHub page](https://github.com/python-poetry/install.python-poetry.org).

2. **Install Project Dependencies**: Once Poetry is installed, navigate to the project directory where `pyproject.toml` is located and run `poetry install`.

3. **Activate Virtual Environment**: Run `poetry shell` to activate the project's virtual environment.

We're in the process of creating more comprehensive Welcome Guides as part of [this ongoing task](https://github.com/alphanome-ai/sec-ai/issues/8). Stay tuned for more!

Feel free to reach out with any questions. Happy coding! 🌟
