### ISSUE TITLE
[TODO] Make a kanban board - project 

### ISSUE THREAD

**Issue by mahimairaja** [alphanome-ai/sec-ai#7]
- I could see the mission and vison of the org, is really great. Make a planner with kanban board or roadmap style. It would be good to start with the milestones...
- Add the project to hacktoberfest
- Add repo maintainers
- Add CI/CD integrations

### Looking forward to connect

**Comment by KakkoAki** [comment]
We can move this discussion here https://github.com/alphanome-ai/sec-ai/discussions/4

**Comment by mahimairaja** [comment]
Done!
